### ISSUE TITLE
NameError: uninitialized constant Wayfarer::Job

### ISSUE THREAD

**Issue by fuzzygroup** [bauerd/wayfarer#2]
So I'm trying to get running with this.  Here's what I did:

1. I created a new rails api project to host all the code related to this
2. I added the wayfarer gem.
3. I did a bundle install.
4.  I created a class in app/models named find_foobar.rb and added the requisite 17 lines per the documentation and the first line was require 'wayfarer'

The error I get is:

FindFoobar.perform_now("https://en.wikipedia.org/wiki/Special:Random")
NameError: uninitialized constant Wayfarer::Job

Any suggestions?  Thanks!

**Comment by bauerd** [comment]
Sorry, just got around to actually pushing to gem. I used this repository more or less as a dumpster before. Please try reinstalling the gem and thanks for the feedback!
